version: 0.2

phases:
  build:
    commands:
      # - command
      - echo Entered the build phase...
      - ls
      - pwd
      - cd backend
      - ls -l
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew bootRepackage
      # - command
  post_build:
    commands:
      # - command
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - cd ./build/libs
      - ls
      - MYPATH=$(pwd)
      - echo $MYPATH
      - zip trips.zip trips-0.1.0.jar
      # - command
artifacts:
  files:
    - trips.zip

